export const SERVER_URL = process.env.REACT_APP_SERVER_URL;
export const SWIPE_TIME = 3200;
export const ANIMATION_TIME = 800;
export const TITLE_WEB = "PARSING VIETNAMESE PUBLICATIONS";
export const TOPIC = "PARSING VIETNAMESE PUBLICATIONS";
