export const SERVER_URL = process.env.REACT_APP_SERVER_URL;
export const SWIPE_TIME = 3200;
export const ANIMATION_TIME = 800;
export const TITLE_WEB = "DETECTION AND TRACKING OF MOTORCYCLES IN AERIAL IMAGE";
export const TOPIC = "DETECTION AND TRACKING OF MOTORCYCLES IN AERIAL IMAGE";
